version: "3.9"

services:
  tradebuddy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - playwright_cache:/app/ms-playwright
      - ./logs:/app/logs

volumes:
  playwright_cache:
