// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Tsutskiridze.TradeBuddy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250506180028_CreatePriceAlertsTable")]
    partial class CreatePriceAlertsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tsutskiridze.TradeBuddy.Core.DBEntities.Telegram.Chat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("TelegramChatID")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.HasKey("ID")
                        .HasName("pk_chats");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("Tsutskiridze.TradeBuddy.Core.DBEntities.Telegram.ChatPriceAlert", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatID")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("StockID")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ID")
                        .HasName("pk_chat_price_alerts");

                    b.HasIndex("ChatID")
                        .HasDatabaseName("ix_chat_price_alerts_chat_id");

                    b.HasIndex("StockID")
                        .HasDatabaseName("ix_chat_price_alerts_stock_id");

                    b.ToTable("chat_price_alerts", (string)null);
                });

            modelBuilder.Entity("Tsutskiridze.TradeBuddy.Core.DBEntities.Telegram.Stock", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("boolean")
                        .HasColumnName("is_watched");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("ID")
                        .HasName("pk_stock");

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("Tsutskiridze.TradeBuddy.Core.DBEntities.Telegram.ChatPriceAlert", b =>
                {
                    b.HasOne("Tsutskiridze.TradeBuddy.Core.DBEntities.Telegram.Chat", "Chat")
                        .WithMany("PriceAlerts")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_price_alerts_chats_chat_id");

                    b.HasOne("Tsutskiridze.TradeBuddy.Core.DBEntities.Telegram.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_price_alerts_stock_stock_id");

                    b.Navigation("Chat");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Tsutskiridze.TradeBuddy.Core.DBEntities.Telegram.Chat", b =>
                {
                    b.Navigation("PriceAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
