syntax = "proto3";

package market_data;

// ===== ENUMS =====
enum QuoteType {
  NONE = 0;
  ALTSYMBOL = 5;
  HEARTBEAT = 7;
  EQUITY = 8;
  INDEX = 9;
  MUTUALFUND = 11;
  MONEYMARKET = 12;
  OPTION = 13;
  CURRENCY = 14;
  WARRANT = 15;
  BOND = 17;
  FUTURE = 18;
  ETF = 20;
  COMMODITY = 23;
  ECNQUOTE = 28;
  CRYPTOCURRENCY = 41;
  INDICATOR = 42;
  CUL_IDX = 43;
  CUL_SUB_IDX = 44;
  CUL_ASSET = 45;
  INDUSTRY = 1000;
}

enum MarketHours {
  PRE_MARKET = 0;
  REGULAR_MARKET = 1;
  POST_MARKET = 2;
  EXTENDED_HOURS_MARKET = 3;
  OVERNIGHT_MARKET = 4;
}

enum OptionType {
  CALL = 0;
  PUT = 1;
}

// ===== MESSAGES =====
message PricingData {
  string id = 1;
  float price = 2;
  sint64 time = 3;
  string currency = 4;
  string exchange = 5;
  QuoteType quote_type = 6;
  MarketHours market_hours = 7;
  float change_percent = 8;
  sint64 day_volume = 9;
  float day_high = 10;
  float day_low = 11;
  float change = 12;
  string short_name = 13;
  sint64 expire_date = 14;
  float open_price = 15;
  float previous_close = 16;
  float strike_price = 17;
  string underlying_symbol = 18;
  sint64 open_interest = 19;
  OptionType options_type = 20;
  bool mini_option = 21;
  sint64 last_size = 22;
  float bid = 23;
  sint64 bid_size = 24;
  float ask = 25;
  sint64 ask_size = 26;
  sint64 price_hint = 27;
  sint64 vol_24hr = 28;
  sint64 vol_all_currencies = 29;
  string fromcurrency = 30;
  string last_market = 31;
  float circulating_supply = 32;
  float marketcap = 33;
  string components = 34;
  repeated string indices = 35;
  sint64 cmc_rank = 36;
  string underlying_shortname = 37;
}

message StaticData {
  string id = 1;
  string display_name = 2;
  string currency = 3;
  string exchange = 4;
  float open_price = 5;
  float close_price = 6;
  float fiftytwo_wk_moving_avg_price = 7;
  float twohundred_data_moving_avg_price = 8;
}

message PriceUpdate {
  PricingData pricing_data = 1;
}

message StaticUpdate {
  StaticData static_data = 1;
}
